"""
Build the publishable static snapshot of the dashboard.

GitHub Pages serves files, not processes: there is nothing there to answer a
request to ``/api/trend``. So this script runs the **real application** in
memory, asks it every question the dashboard asks, and writes each answer to
the file the dashboard will look for instead.

The snapshot is generated by driving ``app.main.create_app()`` through
``TestClient``. No query, no serialiser and no response shape is duplicated
here -- if a route changes, the snapshot changes with it, and the tests that
guard the API guard the snapshot too.

The path mapping, mirrored by ``apiUrl()`` in ``static/index.html``:

====================================  =========================
Live route                            File in the snapshot
====================================  =========================
``/api/health``                       ``api/health.json``
``/api/meta``                         ``api/meta.json``
``/api/indicators``                   ``api/indicators.json``
``/api/trend?indicator=le``           ``api/trend/le.json``
``/api/ranked?type=causes``           ``api/ranked/causes.json``
``/api/export.csv?indicator=le``      ``api/export/le.csv``
====================================  =========================

Usage:

.. code-block:: console

    make site                                   # or, by hand:
    python -m scripts.build_static_site --out site
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path

# Allow `python scripts/build_static_site.py` as well as `python -m ...` by
# putting the repository root on the import path when run as a bare script.
if __package__ in (None, ""):  # pragma: no cover - import bootstrap
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.config import DB_PATH, ROOT_DIR, STATIC_DIR  # noqa: E402

# The ranked charts are the only two-valued axis in the dashboard.
RANK_TYPES = ("causes", "risks")


def _client():
    """Return a TestClient over the real app, seeding the database if needed."""
    from fastapi.testclient import TestClient

    if not DB_PATH.exists():
        from etl.load_seed import load_seed

        load_seed()

    from app.main import create_app

    return TestClient(create_app())


def _write(path: Path, body: str) -> None:
    """Write ``body`` to ``path``, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def _get(client, url: str) -> str:
    """Fetch ``url`` from the in-memory app, failing loudly on any error.

    A snapshot with a missing or half-written file is worse than no snapshot:
    it would publish a dashboard that is broken in a way nobody notices.
    """
    response = client.get(url)
    if response.status_code != 200:
        raise SystemExit(f"FAILED {url} -> HTTP {response.status_code}: {response.text[:200]}")
    return response.text


def build(out_dir: Path) -> dict:
    """Assemble the snapshot in ``out_dir`` and return its manifest."""
    if out_dir.exists():
        shutil.rmtree(out_dir)

    # 1. The dashboard itself: every file the live app serves at "/".
    shutil.copytree(STATIC_DIR, out_dir)

    built_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    files: list[str] = []

    with _client() as client:
        # 2. The fixed routes.
        for route in ("health", "meta", "indicators"):
            body = _get(client, f"/api/{route}")
            if route == "meta":
                # Provenance for the snapshot itself, alongside the round and
                # source the ETL recorded. The dashboard shows it as a chip.
                meta = json.loads(body)
                meta["snapshot_built"] = built_at
                body = json.dumps(meta, indent=2)
            _write(out_dir / "api" / f"{route}.json", body)
            files.append(f"api/{route}.json")

        # 3. One file per indicator, per ranked type -- the whole query space.
        indicators = json.loads((out_dir / "api" / "indicators.json").read_text())
        if not indicators:
            raise SystemExit("Refusing to publish: the database has no indicators.")

        for indicator in indicators:
            ind_id = indicator["indicator_id"]
            _write(
                out_dir / "api" / "trend" / f"{ind_id}.json",
                _get(client, f"/api/trend?indicator={ind_id}"),
            )
            _write(
                out_dir / "api" / "export" / f"{ind_id}.csv",
                _get(client, f"/api/export.csv?indicator={ind_id}"),
            )
            files += [f"api/trend/{ind_id}.json", f"api/export/{ind_id}.csv"]

        for rank_type in RANK_TYPES:
            _write(
                out_dir / "api" / "ranked" / f"{rank_type}.json",
                _get(client, f"/api/ranked?type={rank_type}"),
            )
            files.append(f"api/ranked/{rank_type}.json")

    # 4. Tell the dashboard it is running against files, not a server.
    _write(out_dir / "config.js", STATIC_CONFIG_JS.format(built_at=built_at))

    # 5. Serve the dashboard for unknown paths too, so a stale or mistyped
    #    deep link lands on the site rather than on GitHub's 404 page.
    shutil.copyfile(out_dir / "index.html", out_dir / "404.html")

    # 6. Without this, GitHub Pages runs the output through Jekyll, which
    #    silently drops files and directories whose names begin with "_".
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")

    manifest = {
        "built_at": built_at,
        "indicators": [i["indicator_id"] for i in indicators],
        "ranked_types": list(RANK_TYPES),
        "files": sorted(files),
    }
    _write(out_dir / "api" / "manifest.json", json.dumps(manifest, indent=2))
    return manifest


STATIC_CONFIG_JS = """\
/* Generated by scripts/build_static_site.py -- do not edit by hand.
   Overwrites the committed static/config.js when the snapshot is built,
   which is what switches the dashboard from calling a live API to reading
   the files next to it. Built: {built_at} */
window.API_MODE = "static";
window.SNAPSHOT_BUILT = "{built_at}";
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT_DIR / "site",
        help="Directory to write the snapshot to (default: <repo>/site)",
    )
    args = parser.parse_args()

    manifest = build(args.out)
    print(f"Snapshot written to {args.out}")
    print(f"  {len(manifest['files']) + 4} files, {len(manifest['indicators'])} indicators")
    print(f"  built {manifest['built_at']}")


if __name__ == "__main__":
    main()
