"""
Build the publishable static snapshot of the dashboard.

GitHub Pages serves files, not processes: there is nothing there to answer a
request to ``/api/trend``. So this script runs the **real application** in
memory, asks it every question the dashboard can ask, and writes each answer
to the file the dashboard will look for instead.

The snapshot is generated by driving ``app.main.create_app()`` through
``TestClient``. No query, no serialiser and no figure is duplicated here -- if
a route changes, the snapshot changes with it.

The path mapping, mirrored by ``apiUrl()`` in ``static/index.html``:

=========================================  ===============================
Live route                                 File in the snapshot
=========================================  ===============================
``/api/health``, ``/meta``, ``/series``,   ``api/<name>.json``
``/dimensions``, ``/ranked/options``
``/api/trend?series=ID``                   ``api/trend/ID.json``
``/api/export.csv?series=ID``              ``api/export/ID.csv``
``/api/figure.png?series=ID`` (and pdf)    ``api/figure/ID.png`` (and pdf)
``/api/ranked?type=...&year=...``          ``api/ranked/<file>`` named in
                                           ``api/ranked/options.json``
=========================================  ===============================

A snapshot holds every series over its full year range; the live app's year
range filter has no static equivalent, so the published page hides it.

Usage:

.. code-block:: console

    make site                                   # or, by hand:
    python -m scripts.build_static_site --out site
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path

# Allow `python scripts/build_static_site.py` as well as `python -m ...` by
# putting the repository root on the import path when run as a bare script.
if __package__ in (None, ""):  # pragma: no cover - import bootstrap
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import config  # noqa: E402

RANK_KEYS = ("type", "release", "measure", "metric", "location", "sex", "age", "year")


def _write(path: Path, body: str | bytes) -> None:
    """Write ``body`` to ``path``, creating parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(body, bytes):
        path.write_bytes(body)
    else:
        path.write_text(body, encoding="utf-8")


def _get(client, url: str, params: dict | None = None):
    """Fetch from the in-memory app, failing loudly on any error.

    A snapshot with a missing or half-written file is worse than no snapshot:
    it would publish a dashboard that is broken in a way nobody notices.
    """
    response = client.get(url, params=params)
    if response.status_code != 200:
        raise SystemExit(
            f"FAILED {url} {params or ''} -> HTTP {response.status_code}: " f"{response.text[:200]}"
        )
    return response


def ranked_file(option: dict) -> str:
    """Stable filename for one ranking: a hash, since dimension values are free text."""
    key = json.dumps({k: option[k] for k in RANK_KEYS}, sort_keys=True)
    return "ranked/" + hashlib.blake2b(key.encode(), digest_size=8).hexdigest() + ".json"


def build(out_dir: Path, db_path: Path | None = None) -> dict:
    """Assemble the snapshot in ``out_dir`` and return its manifest."""
    from fastapi.testclient import TestClient

    from app.main import create_app
    from etl.load_seed import ensure_database

    db_path = Path(db_path or config.DB_PATH)
    ensure_database(db_path)  # seeds only if there is nothing usable; never replaces data

    if out_dir.exists():
        shutil.rmtree(out_dir)

    # 1. The dashboard itself: every file the live app serves at "/".
    shutil.copytree(config.STATIC_DIR, out_dir)
    api = out_dir / "api"

    built_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    files: list[str] = []

    def save(relative: str, body: str | bytes) -> None:
        _write(api / relative, body)
        files.append(f"api/{relative}")

    with TestClient(create_app(db_path=db_path)) as client:
        # 2. The fixed routes.
        for route in ("health", "series", "dimensions"):
            save(f"{route}.json", _get(client, f"/api/{route}").text)
        meta = _get(client, "/api/meta").json()
        meta["snapshot_built"] = built_at  # the dashboard shows this as a chip
        save("meta.json", json.dumps(meta, indent=2))

        # 3. Every series, in every format the dashboard offers.
        catalogue = _get(client, "/api/series").json()
        if not catalogue:
            raise SystemExit("Refusing to publish: the database has no series.")
        for entry in catalogue:
            sid = {"series": entry["series_id"]}
            save(f"trend/{sid['series']}.json", _get(client, "/api/trend", sid).text)
            save(f"export/{sid['series']}.csv", _get(client, "/api/export.csv", sid).text)
            for fmt in ("png", "pdf"):
                save(
                    f"figure/{sid['series']}.{fmt}", _get(client, f"/api/figure.{fmt}", sid).content
                )

        # 4. Every ranking, with an index the dashboard looks files up in.
        options = _get(client, "/api/ranked/options").json()
        for option in options:
            option["file"] = ranked_file(option)
            params = {k: option[k] for k in RANK_KEYS}
            save(option["file"], _get(client, "/api/ranked", params).text)
        save("ranked/options.json", json.dumps(options, indent=1))

    # 5. Tell the dashboard it is running against files, not a server.
    _write(out_dir / "config.js", STATIC_CONFIG_JS.format(built_at=built_at))

    # 6. Serve the dashboard for unknown paths too, so a stale or mistyped
    #    deep link lands on the site rather than on GitHub's 404 page.
    shutil.copyfile(out_dir / "index.html", out_dir / "404.html")

    # 7. Without this, GitHub Pages runs the output through Jekyll, which
    #    silently drops files and directories whose names begin with "_".
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")

    manifest = {
        "built_at": built_at,
        "release": meta["release"],
        "series": [e["series_id"] for e in catalogue],
        "rankings": len(options),
        "files": sorted(files),
    }
    _write(api / "manifest.json", json.dumps(manifest, indent=2))
    return manifest


STATIC_CONFIG_JS = """\
/* Generated by scripts/build_static_site.py -- do not edit by hand.
   Overwrites the committed static/config.js when the snapshot is built,
   which is what switches the dashboard from calling a live API to reading
   the files next to it. Built: {built_at} */
window.API_MODE = "static";
window.SNAPSHOT_BUILT = "{built_at}";
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the static GitHub Pages snapshot.")
    parser.add_argument(
        "--out",
        type=Path,
        default=config.ROOT_DIR / "site",
        help="Directory to write the snapshot to (default: <repo>/site)",
    )
    args = parser.parse_args()

    manifest = build(args.out)
    print(f"Snapshot written to {args.out}")
    print(
        f"  {len(manifest['files'])} API files, {len(manifest['series'])} series, "
        f"{manifest['rankings']} rankings, built {manifest['built_at']}"
    )


if __name__ == "__main__":
    main()
